name: Sync Upstream

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch:
  push:
    branches: [main, sync]

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [main, gh-pages]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/adminlby/Hong-Kong-Fire-Documentary.git
          git fetch upstream ${{ matrix.branch }}

      - name: Merge upstream changes
        run: |
          git config user.name "appledailyarchive"
          git config user.email "appledailyarchive@protonmail.com"
          git merge -X theirs upstream/${{ matrix.branch }} --no-edit

      - name: Push changes
        run: |
          git push origin ${{ matrix.branch }}
